import { ColumnDef } from "@tanstack/react-table";
import { fuzzySort } from "../sorter/fuzzySort";

export const contentlist: ColumnDef<any, any>[] = [
  {
    accessorFn: (row) => row.code,
    id: "code",
    header: "코드",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.firstCat,
    id: "firstCat",
    header: "대분류",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.secondCat,
    id: "secondCat",
    header: "중분류",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.pay,
    id: "pay",
    header: "유/무료",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
];

export const contentData = [
  {
    id: "C_B01_P",
    code: "C_B01_P",
    firstCat: "일반 강의",
    secondCat: "일촬",
    pay: "유료",
  },
  {
    id: "C_B01_F",
    code: "C_B01_F",
    firstCat: "일반 강의",
    secondCat: "일촬",
    pay: "무료",
  },
  {
    id: "C_B02_P",
    code: "C_B02_P",
    firstCat: "일반 강의",
    secondCat: "투시",
    pay: "유료",
  },
  {
    id: "C_B02_F",
    code: "C_B02_F",
    firstCat: "일반 강의",
    secondCat: "투시",
    pay: "무료",
  },
  {
    id: "C_B03_P",
    code: "C_B03_P",
    firstCat: "일반 강의",
    secondCat: "CT",
    pay: "유료",
  },
  {
    id: "C_B03_F",
    code: "C_B03_F",
    firstCat: "일반 강의",
    secondCat: "CT",
    pay: "무료",
  },
  {
    id: "C_B04_P",
    code: "C_B04_P",
    firstCat: "일반 강의",
    secondCat: "혈관촬영",
    pay: "유료",
  },
  {
    id: "C_B04_F",
    code: "C_B04_F",
    firstCat: "일반 강의",
    secondCat: "혈관촬영",
    pay: "무료",
  },
  {
    id: "C_B05_P",
    code: "C_B05_P",
    firstCat: "일반 강의",
    secondCat: "심혈관 중재술",
    pay: "유료",
  },
  {
    id: "C_B05_F",
    code: "C_B05_F",
    firstCat: "일반 강의",
    secondCat: "심혈관 중재술",
    pay: "무료",
  },
  {
    id: "C_B06_P",
    code: "C_B06_P",
    firstCat: "일반 강의",
    secondCat: "초음파",
    pay: "유료",
  },
  {
    id: "C_B06_F",
    code: "C_B06_F",
    firstCat: "일반 강의",
    secondCat: "초음파",
    pay: "무료",
  },
  {
    id: "C_B07_P",
    code: "C_B07_P",
    firstCat: "일반 강의",
    secondCat: "MR",
    pay: "유료",
  },
  {
    id: "C_B07_F",
    code: "C_B07_F",
    firstCat: "일반 강의",
    secondCat: "MR",
    pay: "무료",
  },
  {
    id: "C_B08_P",
    code: "C_B08_P",
    firstCat: "일반 강의",
    secondCat: "핵의학",
    pay: "유료",
  },
  {
    id: "C_B08_F",
    code: "C_B08_F",
    firstCat: "일반 강의",
    secondCat: "핵의학",
    pay: "무료",
  },
  {
    id: "C_B09_P",
    code: "C_B09_P",
    firstCat: "일반 강의",
    secondCat: "영상품질관리",
    pay: "유료",
  },
  {
    id: "C_B09_F",
    code: "C_B09_F",
    firstCat: "일반 강의",
    secondCat: "영상품질관리",
    pay: "무료",
  },
  {
    id: "C_C01_P",
    code: "C_C01_P",
    firstCat: "취업",
    secondCat: "면접",
    pay: "유료",
  },
  {
    id: "C_C01_F",
    code: "C_C01_F",
    firstCat: "취업",
    secondCat: "면접",
    pay: "무료",
  },
  {
    id: "C_C02_P",
    code: "C_C02_P",
    firstCat: "취업",
    secondCat: "자소서",
    pay: "유료",
  },
  {
    id: "C_C02_F",
    code: "C_C02_F",
    firstCat: "취업",
    secondCat: "자소서",
    pay: "무료",
  },
  {
    id: "C_C03_P",
    code: "C_C03_P",
    firstCat: "취업",
    secondCat: "대학병원 분석",
    pay: "유료",
  },
  {
    id: "C_C03_F",
    code: "C_C03_F",
    firstCat: "취업",
    secondCat: "대학병원 분석",
    pay: "무료",
  },
  {
    id: "C_D01_P",
    code: "C_D01_P",
    firstCat: "기출 분석",
    secondCat: "N회차 분석",
    pay: "유료",
  },
  {
    id: "C_D01_F",
    code: "C_D01_F",
    firstCat: "기출 분석",
    secondCat: "N회차 분석",
    pay: "무료",
  },
  {
    id: "C_E01_P",
    code: "C_E01_P",
    firstCat: "일반 강의",
    secondCat: "실습",
    pay: "유료",
  },
  {
    id: "C_E01_F",
    code: "C_E01_F",
    firstCat: "일반 강의",
    secondCat: "실습",
    pay: "무료",
  },
];
