import { ColumnDef } from "@tanstack/react-table";
import { fuzzySort } from "../sorter/fuzzySort";

export const contentlist: ColumnDef<any, any>[] = [
  {
    accessorFn: (row) => row.contentName,
    id: "contentName",
    header: "컨텐츠 구분",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.contentCode,
    id: "contentCode",
    header: "컨텐츠 코드",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.firstCat,
    id: "firstCat",
    header: "대분류",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.firstCode,
    id: "firstCode",
    header: "대분류 코드",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.secondCat,
    id: "secondCat",
    header: "중분류",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.secondCode,
    id: "secondCode",
    header: "중분류 코드",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
  {
    accessorFn: (row) => row.code,
    id: "code",
    header: "코드",
    cell: (info) => info.getValue(),
    filterFn: "fuzzy",
    sortingFn: fuzzySort,
  },
];

export const contentData = [
  {
    id: "A_A01",
    code: "A_A01",
    contentName: "ALL",
    contentCode: "A_",
    firstCat: "ALL PASS",
    firstCode: "A",
    secondCat: "ALL CONTENT",
    secondCode: "01",
  },
  {
    id: "C_B01",
    code: "C_B01",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "일촬",
    secondCode: "01",
  },
  {
    id: "C_B02",
    code: "C_B02",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "투시",
    secondCode: "02",
  },
  {
    id: "C_B03",
    code: "C_B03",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "CT",
    secondCode: "03",
  },
  {
    id: "C_B04",
    code: "C_B04",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "혈관촬영",
    secondCode: "04",
  },
  {
    id: "C_B05",
    code: "C_B05",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "심혈관 중재술",
    secondCode: "05",
  },
  {
    id: "C_B06",
    code: "C_B06",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "초음파",
    secondCode: "06",
  },
  {
    id: "C_B07",
    code: "C_B07",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "MR",
    secondCode: "07",
  },
  {
    id: "C_B08",
    code: "C_B08",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "핵의학",
    secondCode: "08",
  },
  {
    id: "C_B09",
    code: "C_B09",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "일반 강의",
    firstCode: "B",
    secondCat: "영상품질관리",
    secondCode: "09",
  },
  {
    id: "C_C01",
    code: "C_C01",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "취업",
    firstCode: "C",
    secondCat: "면접",
    secondCode: "01",
  },
  {
    id: "C_C02",
    code: "C_C02",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "취업",
    firstCode: "C",
    secondCat: "자소서",
    secondCode: "02",
  },
  {
    id: "C_C03",
    code: "C_C03",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "취업",
    firstCode: "C",
    secondCat: "대학병원 분석",
    secondCode: "03",
  },
  {
    id: "C_D01",
    code: "C_D01",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "기출분석",
    firstCode: "D",
    secondCat: "N회차 분석",
    secondCode: "01",
  },
  {
    id: "C_E01",
    code: "C_E01",
    contentName: "CONTENT",
    contentCode: "C_",
    firstCat: "실습",
    firstCode: "E",
    secondCat: "실습",
    secondCode: "01",
  },
];
